name: 'evans-kim/action'

description: 'Deploy with Deployer(forked)'

inputs:

  private-key:
    required: true
    description: The private key for connecting to remote hosts.

  dep:
    required: true
    description: The command.

  known-hosts:
    required: false
    default: ''
    description: Content of `~/.ssh/known_hosts` file.

  ssh-config:
    required: false
    default: ''
    description: The SSH configuration

  deployer-version:
    required: false
    default: ''
    description: Deployer version to download from deployer.org.

  deployer-binary:
    required: false
    default: ''
    description: Path to local Deployer binary.

runs:
  using: 'node12'
  main: 'index.js'

branding:
  color: blue
  icon: send
